[package]
name = "rayhunter-daemon"
version = "0.4.0"
edition = "2021"

[dependencies]
rayhunter = { path = "../lib" }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
